// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using ZomBot.DAL;

namespace ZomBot.Migrations
{
    [DbContext(typeof(BotsDbContext))]
    [Migration("20180220022818_points")]
    partial class points
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ZomBot.Models.LevelModel", b =>
                {
                    b.Property<int>("Level_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Guild");

                    b.Property<int>("Level");

                    b.Property<long>("Messages");

                    b.Property<string>("User");

                    b.Property<long>("User_Id");

                    b.HasKey("Level_Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("ZomBot.Models.PointModel", b =>
                {
                    b.Property<int>("Point_Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Guild");

                    b.Property<long>("Points");

                    b.Property<string>("User");

                    b.Property<long>("User_Id");

                    b.HasKey("Point_Id");

                    b.ToTable("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
